# Generated by Django 3.2.5 on 2022-12-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Key_Broker', '0002_usertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='userid',
        ),
    ]
