# Generated by Django 3.2.5 on 2022-12-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Key_Broker', '0003_remove_usertable_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('guid', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('property_size', models.IntegerField()),
                ('catagory', models.CharField(max_length=250)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
            ],
        ),
    ]
