# Generated by Django 3.2.5 on 2022-12-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Key_Broker', '0006_auto_20221231_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.CharField(max_length=4294967295),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=models.CharField(max_length=4294967295),
        ),
        migrations.AlterField(
            model_name='property',
            name='image4',
            field=models.CharField(max_length=4294967295),
        ),
    ]
