# Generated by Django 3.2.5 on 2022-12-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Key_Broker', '0008_auto_20221231_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_property',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='upload_property',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='upload_property',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='upload_property',
            name='image4',
        ),
    ]
